made simple chat app , usnig socket io

diff --git a/.github/workflows/call-api.yml b/.github/workflows/call-api.yml
--- a/.github/workflows/call-api.yml
+++ b/.github/workflows/call-api.yml
@@ -2,7 +2,7 @@ name: Call Social Media API Every 20 Minutes
 
 on:
   schedule:
-    - cron: '*/20 * * * *'
+    - cron: "*/20 * * * *"
   workflow_dispatch:
 
 jobs:
@@ -10,14 +10,14 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Call API Endpoint
-      run: |
-        response=$(curl -s -o response.txt -w "%{http_code}" "https://node-js-social-media-7t1g.onrender.com/")
-        if [ "$response" != "200" ]; then
-          echo "API call failed with status $response"
-          cat response.txt
-          exit 1
-        else
-          echo "API call succeeded with status $response"
-          cat response.txt
-        fi
+      - name: Call API Endpoint
+        run: |
+          response=$(curl -s -o response.txt -w "%{http_code}" "https://node-js-social-media-7t1g.onrender.com/")
+          if [ "$response" != "200" ]; then
+            echo "API call failed with status $response"
+            cat response.txt
+            exit 1
+          else
+            echo "API call succeeded with status $response"
+            cat response.txt
+          fi
